name: CI Pipeline
run-name: 'PR: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}'

on:
    pull_request:
        branches:
            - main
            - develop
            - 'release/**'

permissions:
    checks: write
    pull-requests: write

env:
    TEST_RESULT_DIR: test-results

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        outputs:
          deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Calculate Cache Key
            id: cache-key
            run: echo "CACHE_KEY=${{ runner.os }}-node-modules-${{ hashFiles('src/package-lock.json') }}" >> "$GITHUB_OUTPUT"

          - name: Cache node_modules
            uses: actions/cache@v4
            id: node_modules_cache
            with:
                key: ${{ steps.cache-key.outputs.CACHE_KEY }}
                path: src/node_modules
                restore-keys: ${{ steps.cache-key.outputs.CACHE_KEY }}

          - name: Restore Dependencies
            if: ${{ steps.node_modules_cache.outputs.cache-hit }}
            run: npm ci
            working-directory: src

    build-core:         
        needs: [install-dependencies]
        runs-on: ubuntu-latest
        
        steps:
            - name: Download Dependecies
              uses: actions/cache@v3
              id: cache
              with:
                path: src/node_modules
                key: ${{ needs.install-dependencies.outputs.deps-cache-key }}
        
            - name: Build
              run: npm run build ngx-configuration -- --configuration production --workspace src

    build-options:
        needs: [install-dependencies]
        runs-on: ubuntu-latest
        
        steps:
            - name: Download Dependecies
              uses: actions/cache@v3
              id: cache
              with:
                path: src/node_modules
                key: ${{ needs.install-dependencies.outputs.deps-cache-key }}
                
            - name: Build
              run: npm run build ngx-options -- --configuration production --workspace src
    
    test:
      needs: [build-core, build-options]
      runs-on: ubuntu-latest
      steps:
          - name: Test
            env:
                JEST_JUNIT_OUTPUT_FILE: ${{ env.TEST_RESULT_DIR }}/tests.unit.xml
                JEST_JUNIT_REPORT_TEST_SUITE_ERRORS: true
            run: |
                npm install jest-junit --save-devs
                npm run test:ci
            working-directory: src
    
          - name: Install TestSpace CLI
            uses: testspace-com/setup-testspace@v1
            with:
                domain: ${{ github.repository_owner }}
    
          - name: Publish Test Results
            run: testspace ${{ env.TEST_RESULT_DIR }}/tests.unit.xml coverage/clover.xml
            working-directory: src
