name: CI Pipeline
run-name: 'PR: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}'

on:
    pull_request:
        branches:
            - main
            - develop
            - 'release/**'

permissions:
    checks: write
    pull-requests: write

env:
    TEST_RESULT_DIR: test-results

jobs:
    install-dependencies:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Calculate Cache Key
            id: cache-key
            outputs:
              deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
            uses: echo "CACHE_KEY=${{ runner.os }}-node-modules-${{ hashFiles('src/package-lock.json') }}" >> "$GITHUB_OUTPUT"

          - name: Cache node_modules
            uses: actions/cache@v4
            id: node_modules_cache
            with:
                key: ${{ steps.cache-key.outputs.CACHE_KEY }}
                path: src/node_modules
                restore-keys: ${{ steps.cache-key.outputs.CACHE_KEY }}

          - name: Restore Dependencies
            if: ${{ steps.node_modules_cache.outputs.cache-hit }}
            run: npm ci

    build-core:
      needs: install-dependecies

      - name: Build
        run: npm run build ngx-configuration

    build-options:
      needs: install-dependecies

      - name: Build
        run: npm run build ngx-configruation-options

    test:
      needs: [build-core, build-options]

      - name: Test
        env:
            JEST_JUNIT_OUTPUT_FILE: ${{ env.TEST_RESULT_DIR }}/tests.unit.xml
            JEST_JUNIT_REPORT_TEST_SUITE_ERRORS: true
        run: |
            npm install jest-junit --save-devs
            npm run test:ci

      - name: Install TestSpace CLI
        uses: testspace-com/setup-testspace@v1
        with:
            domain: ${{ github.repository_owner }}

      - name: Publish Test Results
        run: testspace ${{ env.TEST_RESULT_DIR }}/tests.unit.xml coverage/clover.xml
