name: CI Pipeline
run-name: 'PR: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}'

on:
    pull_request:
        branches:
            - main
            - develop
            - 'release/**'

permissions:
    checks: write
    pull-requests: write

env:
    TEST_RESULT_DIR: test-results

defaults:
  run:
     working-directory: src    

jobs:
    build-core:         
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4           

            - name: Restore Dependencies
              run: npm ci
              working-directory: src
        
            - name: Build
              run: npm run build ngx-configuration-core -- --configuration production
              working-directory: src

    build-options:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4       

            - name: Restore Dependencies
              run: npm ci
              working-directory: src
                
            - name: Build              
              run: npm run build ngx-configuration-options -- --configuration production
              working-directory: src
    
    test:
      needs: [build-core, build-options]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Code
            uses: actions/checkout@v4
              
          - name: Test
            env:
                JEST_JUNIT_OUTPUT_FILE: ${{ env.TEST_RESULT_DIR }}/tests.unit.xml
                JEST_JUNIT_REPORT_TEST_SUITE_ERRORS: true
            run: |
                npm install jest-junit --save-devs
                npm run test:ci
            working-directory: src
    
          - name: Install TestSpace CLI
            uses: testspace-com/setup-testspace@v1
            with:
                domain: ${{ github.repository_owner }}
    
          - name: Publish Test Results
            run: testspace ${{ env.TEST_RESULT_DIR }}/tests.unit.xml coverage/clover.xml
            working-directory: src
