name: CI Pipeline
run-name: PR-${{ github.event.number }}

on: [pull_request]

permissions:
  checks: write
  pull-requests: write

env:
  SOURCE_DIR: src
  TEST_RESULT_DIR: test-results

jobs:
  ng-lib:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Use Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci 
          npm run buil --if-present
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Test
        env:
          JEST_JUNIT_OUTPUT_FILE: ./${{ env.TEST_RESULT_DIR }}/tests.unit.xml
          JEST_JUNIT_REPORT_TEST_SUITE_ERRORS: true
        run: |
          npm install jest-junit --save-devs
          npm run test:ci
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ env.TEST_RESULT_DIR }}/tests.unit.xml
